[13.0][MIG] stock_storage_type
OCA/wms pull request #12
Opened 2020-01-09 14:48 UTC by grindtildeath

Depends on:
 - [ ] https://github.com/OCA/server-tools/pull/1751

Includes:
 - [ ] https://github.com/OCA/wms/pull/7

2020-03-20 13:49 UTC, simahawk reviewed
LG, please rebase and run pre-commit

2020-03-23 11:51 UTC, grindtildeath commented
Rebase done.

@simahawk @guewen @jgrandguillaume Here I'm wondering if we shouldn't merge stock_storage_type_putaway_strategy (#13) into this module, because stock_storage_type only defines fields that are unused and don't make any sense by themselves, i.e. without the other module to compute putaways and restrict stock moves according to storage types...

2020-03-24 10:17 UTC, simahawk commented
@grindtildeath you miss server-tools dependency 
```
odoo.exceptions.UserError: ("You try to install module 'stock_storage_type' that depends on module 'base_m2m_custom_field'.\nBut the latter module is not available in your system.", '')
```

2020-04-24 13:03 UTC, jbaudoux requested changes
What about extracting the location storage type in a separate module that allows to define restrictions on the location (empty, do not mix) without needing package.

This module would add the allowed storage type concept on the location storage type and manage package.

2020-04-24 13:03 UTC, jbaudoux commented on stock_storage_type/models/stock_quant.py
> +            package_quants = quant.package_id.mapped('quant_ids')
The constrain is evaluated at quant creation. At this stage, the package's quant is not up to date.

```
stock.quant(148,)
(Pdb) self.package_id
stock.quant.package(111,)
(Pdb) self.package_id.quant_ids
stock.quant()
```

2020-04-24 13:03 UTC, jbaudoux commented on stock_storage_type/models/stock_quant.py
> +                    ('id', 'not in', package_quants.ids)
We must exclude all previous quants that are not there anymore, i.e. quantity = 0

```suggestion
                    ('id', 'not in', package_quants.ids),
                    ('quantity', '!=', 0)
```

2020-04-24 13:03 UTC, jbaudoux commented on stock_storage_type/models/stock_quant.py
> +                or not pack_storage_type
I would still evaluate the location storage type constrain like do not mix product even if the pack storage type is not defined and even if there is not package. This condition (having a package with a storage type) is only for the "lst_allowed_for_pst" check. For the other checks, we can still apply them based only the location storage type constrain

2020-04-30 06:20 UTC, gurneyalex commented
https://github.com/grindtildeath/wms/pull/5 fixes some performance issues

2020-06-05 16:13 UTC, jbaudoux approved these changes
Thanks for the fixes and perf improvements

2020-06-24 11:10 UTC, jgrandguillaume approved these changes
Tested & approved

2020-06-24 16:04 UTC, grindtildeath commented
I squashed all the commits with a group by authors. Hope this is fine for everyone involved

2020-06-25 09:21 UTC, guewen commented
> I squashed all the commits with a group by authors. Hope this is fine for everyone involved

Not such a big deal, but a commit message that contains 'do X AND Y', pretty often means you should have 2 separate changes.
For instance, the commit that replaces the XML domain by the field domain using web_domain_field was a good atomic commit that I intended to use as an example for a blog post. Now, if you want to understand, you have to read all the commit messages and reverse engineer what part of the commit's diff is related to what part of the commit's message.

Ref good to keep in mind: https://blog.mocoso.co.uk/talks/2015/01/12/telling-stories-through-your-commits/

Anyway, the test should be fixed by my last fixup, I'll squash it if the tests pass.

2020-06-30 08:54 UTC, guewen approved these changes

2020-06-30 08:54 UTC, guewen commented
/ocabot merge patch

2020-06-30 09:07 UTC, merged