[WIP][13.0][MIG] stock_reception_screen
OCA/wms pull request #15
Opened 2020-01-21 11:20 UTC by sebalix

2020-01-23 09:16 UTC, i-vyshnevska commented on stock_reception_screen/models/stock_move.py
> +        related="picking_id.reception_screen_id.current_step"
does current_step of moves have an impact state of the move, in case of done it's ok, but if the screen in "set_pid" step what state move has?

2020-01-23 09:16 UTC, i-vyshnevska commented on stock_reception_screen/models/stock_move.py
> +# Copyright 2019 Camptocamp SA
```suggestion
# Copyright 2020 Camptocamp SA
```
all over the code

2020-01-23 09:16 UTC, i-vyshnevska commented on stock_reception_screen/models/stock_move.py
> +        # self.picking_id.reception_screen_id.button_reset()
```suggestion
```
?

2020-01-23 09:16 UTC, i-vyshnevska commented on stock_reception_screen/models/stock_reception_screen.py
> +        return self.current_move_id.has_tracking != "none"
we don't have different handlings for serial tracking and lots here?
in meaning, if the lot has tracking by serial we can constrain user with qty == 1, before sending data to ORM

2020-01-28 08:46 UTC, gurneyalex commented
Travis is failing because stock_packaging_dimension is not available.

2020-04-06 13:58 UTC, grindtildeath commented on stock_reception_screen/__manifest__.py
> +        "stock_storage_type_putaway_strategy",
```suggestion
        "stock_storage_type",
```

2020-05-20 12:31 UTC, sebalix commented on stock_reception_screen/models/stock_move.py
> +        related="picking_id.reception_screen_id.current_step"
I tested this:

1. I start to process the move of a picking, and stop at the `set_lot_number` step for instance (I let the screen opened)
2. In another window I validate the picking as usual, so all its moves are `done`
3. I get back on the reception screen window, and I'm able to continue all the steps (creating a lot, set a expiry date, put the qty received, set the packaging, the PID...). As the screen mainly updates `stock.move.line` there is no error raised by Odoo. But it is an issue indeed... Some checks have to be added at each step I think to raise an error is the move is already processed (cancel or done).
ping @jgrandguillaume

2020-06-15 07:36 UTC, Tonow-c2c commented
your PR is one [MIG] but we don't have the module history :disappointed_relieved:

2020-07-01 14:44 UTC, jbaudoux requested changes

2020-07-01 14:44 UTC, jbaudoux commented on stock_reception_screen/models/stock_reception_screen.py
> +            not self.current_move_line_product_packaging_id.volume
The volume is in m3 and when the packaging is small, it equals to 0 after roundnig. Can you check instead the length/width/height that are in mm ?

2020-07-06 06:44 UTC, jgrandguillaume commented
@sebalix Can you cehck travis ?

2020-08-27 10:06 UTC, guewen commented
@sebalix FYI I rebased your PR to solve a conflict with oca-dependencies.txt

2020-08-27 11:29 UTC, guewen commented
@sebalix the title says "WIP", still true?

2020-09-23 16:00 UTC, sebalix commented
Last commit 972bba069c775f53e951d2235bfbb10ed7bcd312 depends on https://github.com/OCA/wms/pull/50

@guewen Once #50 is merged I suppose this one is ready for merge too.

2020-09-29 14:21 UTC, jgrandguillaume approved these changes
LGTM, functional test

2020-09-29 14:21 UTC, jgrandguillaume commented
/ocabot merge nobump

2020-09-29 14:57 UTC, sebalix commented
Merge command needs to be relaunch, build failed due to Ubuntu APT repository unavailable:
```
Err:21 http://archive.ubuntu.com/ubuntu xenial InRelease

  Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out [IP: 91.189.88.142 80]

Err:22 http://archive.ubuntu.com/ubuntu xenial-updates InRelease

  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.142 80]

Err:23 http://archive.ubuntu.com/ubuntu xenial-backports InRelease

  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.142 80]

Fetched 5,231 kB in 60s (87.1 kB/s)

Reading package lists...

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out [IP: 91.189.88.142 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.142 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.142 80]

W: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install expect-dev" failed and exited with 100 during .
```

2020-11-03 12:31 UTC, jgrandguillaume commented
/ocabot merge nobump

2020-11-03 16:21 UTC, merged