[13.0][IMP] shopfloor: Add standard messages for Checkout Packing Info
OCA/wms pull request #158
Opened 2021-02-02 09:27 UTC by carlosserratoro

This PR adds the option to choose predefined messages for the
parameter "Checkout Packing Info", that is set on the res.partner
and reused in other places. For this, the original text field
shopfloor_packing_info has been transformed into a Many2one that
points to the new model shopfloor.packing.info. Thus, the field
in the res.partner has been renamed to shopfloor_packing_info_id,
that has caused some renames in other files that used it. These
new messages are archived instead of deleted, to keep track of
old messages associated to existing (or archived) res.partners.

The new predefined messages can be created directly in the partner
or in the menu Inventory > Settings > Shopfloor.

To migrate the data, the existing data has been migrated by assuming
that the first line is the name while all the content is for the text
of the new model.

2021-02-02 10:09 UTC, simahawk requested changes
please don't add another dependency here.
Move this feature to a new module and just hook to _data_for_packing_info

2021-02-02 10:29 UTC, carlosserratoro commented
> please don't add another dependency here.
> Move this feature to a new module and just hook to _data_for_packing_info

@simahawk I'm not sure if I understood you well.

* Regarding the dependency, I assume you mean ```sales_team```. I added it explicitly because it is needed for a permission. It's imported indirectly by the previous dependency that was already there: ```delivery```.

* Regarding the method ```_data_for_packing_info``` I assume you ask for it because the implementation changed. It changed because the field ```shopfloor_packing_info``` is now ```shopfloor_packing_info_id```, and that method uses that variable. The goal was not to add a new field ```shopfloor_packing_info_id```, but to substitute ```shopfloor_packing_info```.

2021-02-02 11:14 UTC, simahawk commented
> > please don't add another dependency here.
> > Move this feature to a new module and just hook to _data_for_packing_info
> 
> @simahawk I'm not sure if I understood you well.
> 
>     * Regarding the dependency, I assume you mean `sales_team`. I added it explicitly because it is needed for a permission. It's imported indirectly by the previous dependency that was already there: `delivery`.
> 
>     * Regarding the method `_data_for_packing_info` I assume you ask for it because the implementation changed. It changed because the field `shopfloor_packing_info` is now `shopfloor_packing_info_id`, and that method uses that variable. The goal was not to add a new field `shopfloor_packing_info_id`, but to substitute `shopfloor_packing_info`.

ok, but still: split it :wink:

2021-02-03 07:28 UTC, carlosserratoro commented
@simahawk Do you want to keep the field ```shopfloor_display_packing_info``` in the module ```shopfloor``` or do I extract it to the new module? If extracted, the method ```_data_for_packing_info``` will be just a placeholder returning the empty string in ```shopfloor``` and intended to be extended only.

2021-02-03 07:47 UTC, simahawk commented
> @simahawk Do you want to keep the field `shopfloor_display_packing_info` in the module `shopfloor` or do I extract it to the new module? If extracted, the method `_data_for_packing_info` will be just a placeholder returning the empty string in `shopfloor` and intended to be extended only.

Yes, leave it as hook to provide that info.

2021-02-03 13:03 UTC, closed without merging

2021-02-03 13:12 UTC, carlosserratoro commented
Closed because was substituted by https://github.com/OCA/wms/pull/161.