[14.0] shopfloor: added support for multiple barcodes
OCA/wms pull request #284
Opened 2021-09-01 16:12 UTC by hparfr

2021-09-06 14:00 UTC, simahawk requested changes

2021-09-06 14:00 UTC, simahawk commented on shopfloor/__manifest__.py
> +        "product_multi_barcode",
shall we move this feature to a glue module `shopfloor_product_multi_barcode`?

2021-09-06 14:00 UTC, simahawk commented on shopfloor/actions/search.py
> +            ["|", ("barcode", "=", barcode), ("barcode_ids.name", "=", barcode)],
we can split the domain generation to a separated method to be able to override it from the other module

2021-09-07 07:13 UTC, hparfr commented
Yep, that the kind of feature you see as a must have, but not every implementation need / want it.
I want some of the scenarios (like reception) be part of shopfloor and use multibarcode.

So instead of making these changes, what do you think @simahawk of change all scenarios and always use `barcodes` or `barcode_ids` in all shopfloor(_.+)* modules? In that way, the support of multibarcode is everywhere and can be opted-in with the installation of glue shopfloor_barcode"
with a default implementation in shopfloor like : 
```py
barcodes = [ product.barcode ]
# or 
barcode_ids = [ {"id": False, "name": product.barcode } ]
```

2021-12-14 13:45 UTC, hparfr commented
ping @sebastienbeau

2022-04-28 06:39 UTC, simahawk commented
> Yep, that the kind of feature you see as a must have, but not every implementation need / want it. I want some of the scenarios (like reception) be part of shopfloor and use multibarcode.
> 
> So instead of making these changes, what do you think @simahawk of change all scenarios and always use `barcodes` or `barcode_ids` in all shopfloor(_.+)* modules? In that way, the support of multibarcode is everywhere and can be opted-in with the installation of glue shopfloor_barcode" with a default implementation in shopfloor like :
> 
> ```python
> barcodes = [ product.barcode ]
> # or 
> barcode_ids = [ {"id": False, "name": product.barcode } ]
> ```

You mean that the UI should always expect a list?
BTW is it useful to expose the IDs?

2022-04-28 07:54 UTC, hparfr commented
> You mean that the UI should always expect a list?


No, you only scan one barcode.
The use case is when you have to consider two products with different barcode to be identical.

>BTW is it useful to expose the IDs?

Yes, I need it when scanning two products in a row to detect if we are scanning the same product or not.

2022-04-28 08:58 UTC, simahawk commented
> > You mean that the UI should always expect a list?
> 
> No, you only scan one barcode. The use case is when you have to consider two products with different barcode to be identical.

You got me wrong: I mean that if you want to support multiple barcodes seamlessly on the front, you have to expect a list of barcodes back when you return the product info and display them accordingly where needed.

> > BTW is it useful to expose the IDs?
> 
> Yes, I need it when scanning two products in a row to detect if we are scanning the same product or not.

but here you search only by name -> the ID seems useless

2022-10-09 12:11 UTC, closed without merging