14 raise instead dict
OCA/wms pull request #420
Opened 2022-06-15 08:43 UTC by bguillot

Hi,

This PR replace error messages returned to the app by raises.
It allows  to handle rollback more easily and avoid to take care of the return of methods in case of nested methods. 
For instance if a method returns a recordset but sometimes if error appends it returns dict of error message, so you have to check if the return is dict, and be sure that it will follow all the way down.

I did on one scenario to show the differences. We can change for the others after that.

2023-03-03 11:03 UTC, sebastienbeau commented
@lmignon

2023-03-03 14:40 UTC, lmignon approved these changes
IMO it's a must have... It restore 'normal' behavior when a process encounter an error into a python program.

2023-03-05 14:21 UTC, simahawk requested changes
@bguillot can you rebase?

2023-03-05 14:21 UTC, simahawk commented on shopfloor_base/__init__.py
> +from . import exceptions
there's no need to import this file

2023-03-05 14:21 UTC, simahawk commented on shopfloor_base/exceptions.py
> +        payload["no_wrap"] = True
can you document this flag?

2023-03-05 14:21 UTC, simahawk commented on shopfloor_rest_log/components/service.py
> +            if isinstance(orig_exception, ShopfloorError):
can you add a test for this?

2023-08-13 12:07 UTC, closed without merging