14.0  shopfloor checkout  prevent more than planned
OCA/wms pull request #525
Opened 2023-01-04 15:19 UTC by JuMiSanAr

For checkout, in the select_package screen, we now allow the user to scan articles and go beyond the maximum qty_done allowed (line will be highlighted in red and a warning message will be displayed).

However, assigning a package in that situation will not be allowed, and they will still receive an error message.

Depends on:
- https://github.com/OCA/wms/pull/483#issuecomment-1370958786

ref: rau-92

2023-01-09 13:09 UTC, simahawk requested changes

2023-01-09 13:09 UTC, simahawk commented on shopfloor/services/checkout.py
> +        for line in selected_lines:
this loop is repeat 3 times: can we put it in its own method?

2023-06-05 07:26 UTC, jbaudoux approved these changes
Tested

2023-06-05 07:30 UTC, jbaudoux commented
rebased

2023-06-05 12:31 UTC, simahawk approved these changes

2023-06-05 12:31 UTC, simahawk commented
/ocabot merge minor

2023-06-05 13:03 UTC, merged