[14.0][IMP] stock_available_to_promise_release
OCA/wms pull request #527
Opened 2023-01-05 09:16 UTC by mt-software-de

own method for checking if a move is releasable

2023-01-05 10:39 UTC, mt-software-de commented
fyi @jbaudoux

2023-01-05 12:02 UTC, jbaudoux approved these changes

2023-01-05 12:02 UTC, jbaudoux commented
@sebalix Can you review & merge this one?

2023-01-09 13:00 UTC, simahawk requested changes
In addition can you please rewrite the commit msg to smth like:

```
[IMP] s_available_to_promise_release: add hook before release

Split _run_stock_rule to offer more hooks for override.
```

2023-01-09 13:00 UTC, simahawk commented on stock_available_to_promise_release/models/stock_move.py
> +        if self._get_release_remaining_qty():
The computation of the qty now happens 2 times on each iteration.
It would be better to make `_is_releasable` return the qty and use it right after at line 339.

2023-01-09 13:36 UTC, mt-software-de commented on stock_available_to_promise_release/models/stock_move.py
> +        if self._get_release_remaining_qty():
yes you are right, now _is_releaseable is returning the available_qty and the remaining_qty

2023-01-10 09:58 UTC, sebalix commented
@mt-software-de you can remove the `[14.0]` from commit message, as it has no value once ported to next versions (or backported).

2023-01-10 10:00 UTC, mt-software-de commented
> @mt-software-de you can remove the `[14.0]` from commit message, as it has no value once ported to next versions (or backported).

yes

2023-01-10 13:43 UTC, sebalix approved these changes

2023-01-11 10:13 UTC, sebalix commented
/ocabot merge minor

2023-01-11 10:30 UTC, merged