[14.0] shopfloor zone_picking: block move selection
OCA/wms pull request #631
Opened 2023-05-10 14:05 UTC by JuMiSanAr

Until now, in the mobile version of the zone_picking scenario, we were allowed to select manually a move by clicking on it. This is not the case anymore.

ref: rau-153

2023-05-17 08:03 UTC, jbaudoux requested changes
We should not loose the condensed display on mobile. Can"t switch manual-select to item-detail-card ?

2023-05-17 09:29 UTC, JuMiSanAr commented
> We should not loose the condensed display on mobile. Can"t switch manual-select to item-detail-card ?

Yes. I've attached a screenshot of how that looks like to this PR, let me know if that's ok.

2023-05-17 09:40 UTC, jbaudoux approved these changes
Thanks. Looks good now :)

2023-05-30 06:38 UTC, mt-software-de approved these changes
LGTM

2023-05-30 07:34 UTC, jbaudoux commented
/ocabot merge minor

2023-05-30 07:54 UTC, merged