[14.0] shopfloor_single_product_transfer: allow to scan packages
OCA/wms pull request #635
Opened 2023-05-15 13:38 UTC by JuMiSanAr

Now the user can scan packages on the first screen (before, only locations were allowed).

ref: rau-146

- [x] Add tests for scan_location endpoint.

Depends on:
- https://github.com/OCA/wms/pull/513
- https://github.com/OCA/wms/pull/520

2023-05-16 06:05 UTC, jbaudoux requested changes

2023-05-16 06:05 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> +        lines_without_package = self.env["stock.move.line"].search(
checking existing move lines should be only if allow_create_moves is False
In _scan_location__check_stock, I would also add a check that if all the quants in the location are part of a package, you have to scan a package

2023-05-16 06:05 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> +            ]
add `"(state", "in", ("assigned", "partially_available"))`

2023-05-16 06:05 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> +        if package.location_id not in allowed_locations:
Use instead `if not self.is_src_location_valid(package.location_id)`

Do the same change in `_scan_location__check_location`

2023-05-16 06:35 UTC, jbaudoux requested changes

2023-05-16 06:35 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> -                ("picking_id.picking_type_id", "in", self.picking_types.ids),
I would have kept this `("picking_id.picking_type_id", "in", self.picking_types.ids)`

2023-05-16 06:35 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> +            domain = AND([domain, [("package_id", "=", package.id)]])
If no package, do not match a line with package
`domain = AND([domain, [("package_id", "=", package.id if package else False)]])`

2023-05-16 06:35 UTC, jbaudoux commented on shopfloor_single_product_transfer/services/single_product_transfer.py
> +            move_vals["package_id"] = package.id
This field does not exist. You need to leverage forced_package_id in the action_assign().
I would create a package_level and set it on the move after action_confirm. This way the move has a picking_id you can use on the package level creation.

2023-05-26 15:43 UTC, closed without merging

2023-05-26 15:44 UTC, JuMiSanAr commented
Closed as this work is already included in https://github.com/OCA/wms/pull/640