[16.0][ADD] stock_release_channel_delivery
OCA/wms pull request #636
Opened 2023-05-15 17:36 UTC by glitchov

This addon adds a field containing the carrier linked to the release channel. 
Though an overlap can be seen on the picking point of view as the
rule_domain does the job the idea is to easy link the channel with the
customer.

2023-10-09 10:09 UTC, jbaudoux approved these changes

2023-10-09 10:10 UTC, jbaudoux commented
/ocabot rebase

2023-10-09 10:13 UTC, jbaudoux commented
@sbejaoui Can you rebase, it seems failing tests are not related to this PR

2023-10-09 11:19 UTC, sbejaoui commented
> @sbejaoui Can you rebase, it seems failing tests are not related to this PR

done

2023-10-09 20:44 UTC, jbaudoux requested changes
We cannot be so restrictive to only one shipping method on the release channel.

In odoo, there are some providers requiring to create one shipping method for national deliveries and another one for international deliveries. However they are usually managed the same way in the warehouse and classified on the same release channel.

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/__manifest__.py
> +        Exposes clearly the carrier linked to the release channel """,
```suggestion
        Add a carrier selection criteria on the release channel """,
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/models/stock_picking.py
> +        if self.carrier_id:
```suggestion
        if self.carrier_ids:
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/models/stock_picking.py
> +                    ("carrier_id", "=", self.carrier_id.id),
```suggestion
                    ("carrier_ids", "=", False),
                    ("carrier_ids", "in", self.carrier_id.ids),
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/models/stock_release_channel.py
> +    carrier_id = fields.Many2one(
```suggestion
    carrier_ids = fields.Many2many(
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/models/stock_release_channel.py
> +        string="Transporter",
```suggestion
        string="Shipping Methods",
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/readme/DESCRIPTION.rst
> +customer.
```suggestion
This addon adds a selection criteria on the release channel based on the shipping method.
When you don't classify your deliveries in different operation types per shipping method, then you can use this criteria to filter the selection of valid release channels. While you could achieve the same with the domain provided on the base release channel module, this criteria provides a more explicit configuration and also performs better.
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/views/stock_release_channel_views.xml
> +                <field name="carrier_id" />
```suggestion
                <field name="carrier_ids" widget="many2many_tags"/>
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/tests/test_release_channel_delivery.py
> +        self.channel.carrier_id = self.carrier
```suggestion
        self.channel.carrier_ids = self.carrier
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/tests/test_release_channel_delivery.py
> +        self.channel.carrier_id = False
```suggestion
        self.channel.carrier_ids = False
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/tests/test_release_channel_delivery.py
> +        self.channel.carrier_id = self.carrier2
```suggestion
        self.channel.carrier_ids = self.carrier2
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/__manifest__.py
> +    "author": "ACSONE SA/NV,Odoo Community Association (OCA)",
```suggestion
    "author": "ACSONE SA/NV,BCIM,Odoo Community Association (OCA)",
```

2023-10-09 20:44 UTC, jbaudoux commented on stock_release_channel_delivery/readme/CONTRIBUTORS.rst
> +* Hughes Damry <hughes.damry@acsone.eu>
```suggestion
* Hughes Damry <hughes.damry@acsone.eu>
* Jacques-Etienne Baudoux (BCIM) <je@bcim.be>
```

2023-10-17 07:50 UTC, simahawk commented
@glitchov are you planning to move fwd soon here? Otherwise we could take over.

2023-11-14 08:53 UTC, simahawk commented
ping :)

2024-01-30 11:08 UTC, lmignon commented
@simahawk We are stuck on stabilizing our Odoo 16 instance.... We've no time to manage the change and the migration of a `Many2one` to `Many2many` field type for the carrier on the release channel model.

2024-02-22 15:23 UTC, jbaudoux commented
replaced by https://github.com/OCA/wms/pull/840

2024-02-22 15:23 UTC, closed without merging