[14.0] shopfloor_delivery_shipment: some improvements to load trucks
OCA/wms pull request #649
Opened 2023-06-08 14:50 UTC by sebalix

Some changes are required on the front-end part, will be done later (maybe in another PR).

Ref. rau-154

2023-06-08 15:43 UTC, jbaudoux requested changes
I hope it loads quickly even when all_lines_to_load is more than a 1000
before it's reduced to a few that are in partially loaded picking

2023-06-08 15:43 UTC, jbaudoux commented on shopfloor_delivery_shipment/services/delivery_shipment.py
> +        move_lines = self.env["stock.move.line"].search(domain)
Looking at `_find_move_lines_domain`, I think this should only apply if there is no planned moves on the shipment advice
```
if not shipment_advice.planned_move_ids:
   ...
```

2023-06-08 15:49 UTC, jbaudoux commented
It would be good to move this feature out of shopfloor and put it on the shipment advice.
I would even have put an action to list those moves lines grouped by package from a shipment advice. That's a useful control report from a shipment advice without having to open shopfloor.

Nice to have, non blocking, #ReduceCodeInShopfloor

2023-06-09 10:46 UTC, TDu approved these changes

2023-06-09 11:41 UTC, sebalix commented on shopfloor_delivery_shipment/services/delivery_shipment.py
> +        move_lines = self.env["stock.move.line"].search(domain)
Done. I also moved and adapted the `_find_move_lines_domain` to `shipment_advice` module.

2023-06-09 11:47 UTC, sebalix commented
@jbaudoux this PR now depends on https://github.com/OCA/stock-logistics-transport/pull/96

2023-06-27 12:42 UTC, jbaudoux approved these changes

2023-06-28 11:23 UTC, jbaudoux commented
/ocabot merge minor

2023-06-28 11:44 UTC, merged