[14.0][IMP] generic_compute_picking_count_release_channel
OCA/wms pull request #654
Opened 2023-06-13 10:34 UTC by marcwimmer

Allows in dependant modules to add additional aggregation columns like volumes for example and avoids a cost intensive group by read on open pickings.

A possible function in a dependant module would look like this then:

`    @api.model
    def _compute_picking_count_additional_fields(self):
        return ["volume"]

    def _compute_picking_count(self):
        (
            domains,
            domain_data,
            stock_move_aggregated_by_picking,
            picking_ids_per_field,
        ) = super()._compute_picking_count()

        dimension = 'volume'
        for picking_field, __ in domains.items():
            data = domain_data[picking_field]
            move_field = picking_field.replace("picking", "move")
            picking_volumes = {
                row["release_channel_id"][0]: row["volume"]
                for row in data
                if row["release_channel_id"]
            }

            for rec in self:
                rec[picking_field + "_" + dimension] = picking_volumes.get(rec.id, 0)

                digits = self._fields[move_field + "_volume"].get_digits(rec.env)[1]
                picking_ids = picking_ids_per_field.get((rec.id, picking_field), [0])
                volumes = stock_move_aggregated_by_picking[dimension]
                sum_volume = sum(
                    volumes.get(picking_id, 0) for picking_id in picking_ids
                )
                rec[move_field + "_" + dimension] = float_round(sum_volume, digits)

        for record in self:
            record.count_picking_full_progress_volume = (
                record.count_picking_release_ready_volume
                + record.count_picking_released_volume
                + record.count_picking_done_volume
            )
`

2023-06-14 20:09 UTC, mt-software-de requested changes
If we would do it roughly as shown here, we don't need to overwrite `_compute_picking_count`.
It would be then enough to add the additional fields to `_get_additional_picking_read_group_fields` or `_get_additional_move_read_group_fields`

As you can see in the example here.
`def _get_additional_picking_read_group_fields():
    return ["volume:sum"]`

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +        return []
```suggestion
    @api.model
    def _get_additional_picking_read_group_fields(self):
        return []

    @api.model
    def _get_additional_move_read_group_fields(self):
        return []
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
>          domains = self._field_picking_domains()
```suggestion
        domains = self._field_picking_domains()
        additional_picking_fields = self._get_additional_picking_read_group_fields()
        additional_move_fields = self._get_additional_move_read_group_fields()
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +                ["release_channel_id", "picking_ids:array_agg(id)"] + self._compute_picking_count_additional_fields(),
```suggestion
                ["release_channel_id", "picking_ids:array_agg(id)"] + additional_picking_fields,
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +
```suggestion
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +            ["picking_id"] + self._compute_picking_count_additional_fields(),
```suggestion
            ["picking_id"] + additional_move_fields,
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +            domain_data[field] = data
```suggestion
                picking_field_prefix = field.replace("count_")
                for additional_field in additional_picking_fields:
                    additional_field = additional_field.split(":")[0]
                    additional_field_name = "{picking_field_prefix}_{additional_field}"
                    record[additional_field_name] = record_group_data[additional_field]
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
>                  record[field] = count.get(record.id, 0)
```suggestion
                record_group_data = count.get(record.id, {})
                record[field] = record_group_data and record_group_data["release_channel_id_count"]
```

Therefore line 226 or in your change line 233 must be changed, add the row instead of row["release... to the count dict

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +        return domains, domain_data, stock_move_aggregated_by_picking, picking_ids_per_field
```suggestion
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
>              row["picking_id"][0]: row["picking_id_count"]
```suggestion
            row["picking_id"][0]: row
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
> +            })
```suggestion
```

2023-06-14 20:09 UTC, mt-software-de commented on stock_release_channel/models/stock_release_channel.py
>              for record in self:
```suggestion
            move_field = field.replace("picking", "move")
            additional_field_prefix = move_field.replace("count_", "")
            for record in self:
                picking_ids = picking_ids_per_field.get((record.id, field), [])
                move_estimate = sum(
                    move_count.get(picking_id, {}).get("picking_id_count", 0) for picking_id in picking_ids
                )
                record[move_field] = move_estimate
                for additional_field in additional_move_fields:
                    additional_field = additional_field.split(":")[0]
                    additional_field_name = "{additional_field_prefix}_{additional_field}"
                    _sum = sum(
                        move_count.get(picking_id, {}).get(additional_field, 0) for picking_id in picking_ids
                    )
```

2023-06-19 07:08 UTC, closed without merging

2023-06-19 07:09 UTC, marcwimmer commented
decision is to slice the original function into reusable parts; so no overwrite of _compute_picking_count needed