[14.0][IMP] stock_warehouse_flow: assign_picking only if needed
OCA/wms pull request #682
Opened 2023-07-19 03:07 UTC by mt-software-de

Do not call assign_picking on apply
if it is getting called from action_confirm

cc @jbaudoux

2023-07-19 06:48 UTC, mt-software-de commented
@sebalix and @jbaudoux could also please review this one?

2023-07-19 07:04 UTC, jbaudoux reviewed
I guess we lack a unit test for checking that after the flow is applied the delivery can be inside a different release channel

2023-07-19 07:05 UTC, jbaudoux commented on stock_warehouse_flow/models/stock_move.py
> +            flow._apply_on_move(move, assign_picking=False)
A comment why you do this would be helpful for the future

2023-07-19 08:32 UTC, mt-software-de commented
> I guess we lack a unit test for checking that after the flow is applied the delivery can be inside a different release channel
yes but this should only occur if stock_release_channel and stock_warehouse_flow would be installed

2023-07-19 09:04 UTC, jbaudoux commented
> > I guess we lack a unit test for checking that after the flow is applied the delivery can be inside a different release channel

> yes but this should only occur if stock_release_channel and stock_warehouse_flow would be installed

Then we need a glue module that auto install. This module can contain just that test.

2023-08-02 14:34 UTC, RodrigoBM requested changes

2023-08-02 14:34 UTC, RodrigoBM commented on stock_warehouse_flow/models/stock_warehouse_flow.py
> +            flow._apply_on_move(move, assign_picking)
```suggestion
            flow._apply_on_move(move, assign_picking=assign_picking)
```

2023-08-02 19:52 UTC, mt-software-de commented on stock_warehouse_flow/models/stock_warehouse_flow.py
> +        return flows.apply_on_move(move, assign_picking)
Thx for your Review.
I am fine with calling the Method without the Keyword.

2023-08-23 03:37 UTC, jbaudoux approved these changes

2023-08-23 03:41 UTC, jbaudoux commented
/ocabot merge patch

2023-08-23 06:18 UTC, merged