[IMP] shopfloor_mobile_base: Display manual-select list-items separted
OCA/wms pull request #683
Opened 2023-07-19 11:58 UTC by mt-software-de

This allows to display the list-items of the manual-select component as separate items. 
Set list_items_separated = true
Then it will display the items like this
![image](https://github.com/OCA/wms/assets/78783475/6a5534dd-e468-43eb-a8bb-11e774f82105)
instead of
![image](https://github.com/OCA/wms/assets/78783475/654c5bc4-9c1e-4ad5-b569-4665535abc63)

2023-07-19 11:59 UTC, mt-software-de commented
cc @jbaudoux @simahawk

2023-07-20 11:26 UTC, simahawk requested changes
Thanks for you contrib, few discussion items:

* I'm not sure we need a specific param for this... `card_klass` should be enough
* can we avoid defining our own shadow rules? It could be possible to get them from vuetifyjs
* we should support the same in list.js IMO
*

2023-07-20 11:52 UTC, mt-software-de commented
> * vuetifyjs

2023-07-20 12:25 UTC, mt-software-de commented
> Thanks for you contrib, few discussion items:
> 
>     * I'm not sure we need a specific param for this... `card_klass` should be enough

I would provide a specific parameter as that makes it easier to know what the component is capable of . 

> 
>     * can we avoid defining our own shadow rules? It could be possible to get them from vuetifyjs

i have found .v-stepper this is adding the same shadow so we can use this.

> 
>     * we should support the same in list.js IMO
Yes this would be good.

2023-07-26 07:02 UTC, simahawk approved these changes

2023-07-26 08:17 UTC, jbaudoux reviewed
We can improve how the list is displayed but I don't think we should have different display in different scenario.
I liked the fact that each element is inside the same box. Maybe just a line separator is enough. This is displayed on a mobile screen and we should not loose vertical space.
Just my opinion...

2023-07-26 08:32 UTC, mt-software-de commented
> We can improve how the list is displayed but I don't think we should have different display in different scenario. I liked the fact that each element is inside the same box. Maybe just a line separator is enough. This is displayed on a mobile screen and we should not loose vertical space. Just my opinion...

Yes we are loosing some space with this option, but this is not fixed. 
I wanted to achieve a lookalike of the item-detail-card.

2023-11-06 08:54 UTC, mt-software-de commented
How should we go on with that PR? Should we merge it?
Or close it? Maybe a better solution would be to introduce different themes for the shopfloor app?

2024-04-14 14:34 UTC, closed without merging