[ADD] stock_release_channel_plan_process_end_time
OCA/wms pull request #696
Opened 2023-07-28 16:06 UTC by jbaudoux

Glue module between:

- https://github.com/OCA/wms/pull/55
- https://github.com/OCA/wms/pull/695

2023-08-01 09:44 UTC, lmignon requested changes
Can you add in a specific commit a test-requirements.txt file with the dependent PR as it's done here https://github.com/OCA/wms/pull/693/commits/758b160304e097300932c358c7dd8bc915db0c45

2023-08-02 07:36 UTC, jbaudoux commented
> Can you add in a specific commit a test-requirements.txt file with the dependent PR as it's done here [758b160](https://github.com/OCA/wms/commit/758b160304e097300932c358c7dd8bc915db0c45)

Done. The failing test is not on this PR but on https://github.com/OCA/wms/pull/550

2023-10-06 15:25 UTC, simahawk commented on stock_release_channel_plan_process_end_time/tests/test_stock_release_channel_plan.py
> +    test_stock_release_channel_plan.TestStockReleaseChannelPlan
hmm I'm not in favor of inheriting full test classes as every test you add there will run twice here.
Also overriding the method and calling super seems weird...
Can't you add a mixin and reuse it here?

2024-01-23 17:26 UTC, grindtildeath commented
https://github.com/jbaudoux/wms/pull/2

2024-03-27 10:17 UTC, jbaudoux commented
rebased & dropped do not merge commit

2024-03-27 10:30 UTC, jbaudoux commented on stock_release_channel_plan_process_end_time/tests/test_stock_release_channel_plan.py
> +    test_stock_release_channel_plan.TestStockReleaseChannelPlan
done

2024-03-27 12:28 UTC, jbaudoux commented
Tests have been fixed. Can you update your review @lmignon @simahawk 

cc @sebalix

2024-03-28 07:15 UTC, lmignon commented
@jbaudoux This one will collide with stock_release_channel_end_time. Once installed, it's no more possible to let the `process_end_date` be computed by default since it's a required field on the wizard. Moreover, the `process_end_date` is set by default to 'today'. As result when you launch the wizard with release channels configured with a `process_end_time` prior to the current time, the new computed `process_end_date` for the release channels will be in the past. What do you think about?

2024-03-29 07:55 UTC, sbejaoui approved these changes
code review + functional test

2024-04-02 09:18 UTC, lmignon approved these changes

2024-04-03 15:16 UTC, jbaudoux commented
/ocabot merge minor

2024-04-03 15:24 UTC, merged