[14][IMP] shopfloor_delivery_shipment improve confirmation of shipment creation
OCA/wms pull request #709
Opened 2023-08-04 13:34 UTC by TDu

2023-08-21 13:56 UTC, jbaudoux approved these changes

2023-08-23 03:31 UTC, jbaudoux requested changes

2023-08-23 03:31 UTC, jbaudoux commented on shopfloor_delivery_shipment/services/delivery_shipment.py
> +                        confirmation_required=dock.barcode,
```suggestion
                        confirmation_required=barcode,
```

2023-08-23 03:31 UTC, jbaudoux commented on shopfloor_delivery_shipment/services/delivery_shipment.py
> +                if confirmation != dock.barcode:
```suggestion
                if confirmation != barcode:
```

2023-08-23 03:31 UTC, jbaudoux commented on shopfloor_delivery_shipment/services/delivery_shipment.py
> +                        confirmation_required=dock.barcode,
```suggestion
                        confirmation_required=barcode,
```

2023-08-24 08:54 UTC, TDu commented
Rebased, did the changes requested

2023-08-24 12:05 UTC, jbaudoux approved these changes

2023-08-24 12:06 UTC, jbaudoux commented
/ocabot merge patch

2023-08-24 12:31 UTC, merged