[14.0][IMP] shopfloor zone picking improve select_line endpoint/state
OCA/wms pull request #727
Opened 2023-08-17 12:03 UTC by TDu

2023-08-21 13:53 UTC, jbaudoux requested changes

2023-08-21 13:53 UTC, jbaudoux commented on shopfloor_mobile/static/wms/src/scenario/zone_picking.js
>                              }
```
                            if (this.state.data.scan_location_or_pack_first)
                                if (!pack && this.all_lines_with_package() {
                                    return "Scan pack";
                                }
                                if (!sublocation && !pack) {
                                    return "Scan location / pack";
                                }
                                if (any_line_with_lot) {
                                    return "Scan product / lot";
                                } else {
                                    return "Scan product";
                                }
                            }
```

2023-08-21 13:53 UTC, jbaudoux commented on shopfloor_mobile/static/wms/src/scenario/zone_picking.js
> +                            }
```
if sublocation
  if pack
    if any_line_with_lot
      scan product / lot
    scan product
  else
    if any_line_with_lot
      scan pack / product / lot
    scan pack /product
else
  if any_line_with_lot
    scan location / pack / product / lot
  scan location / pack /product
```

2023-08-22 22:04 UTC, jbaudoux commented on shopfloor_mobile/static/wms/src/scenario/zone_picking.js
> +                                }
pack / product / lot
Why having pack after product? Or product / lot / pack


pack / product ?

2023-08-23 13:13 UTC, TDu commented on shopfloor_mobile/static/wms/src/scenario/zone_picking.js
> +                                }
changed

2023-08-23 13:33 UTC, jbaudoux approved these changes

2023-08-23 13:33 UTC, jbaudoux commented
@TDu Can you squash the fixups?

2023-08-23 14:55 UTC, TDu commented
squashed

2023-08-23 21:28 UTC, jbaudoux commented
rebased

2023-08-28 11:13 UTC, mmequignon approved these changes

2023-08-28 12:28 UTC, jbaudoux commented
/ocabot merge minor

2023-08-28 12:53 UTC, merged