[16.0][ADD] stock_release_channel_cutoff
OCA/wms pull request #740
Opened 2023-09-08 04:34 UTC by QuocDuong1306

This module lets users select a release channel and set a specific cutoff time for it.

When the current time (now) becomes later than the cutoff time, the kanban view for that channel will display the cutoff time in red as a warning.

2023-09-13 11:07 UTC, cyrilmanuel approved these changes

2023-09-13 11:30 UTC, leemannd approved these changes

2023-09-14 13:05 UTC, jbaudoux requested changes

2023-09-14 13:05 UTC, jbaudoux commented on stock_release_channel_cutoff/models/stock_release_channel.py
> +    cutoff_datetime = fields.Datetime()
We only need the cutoff_time. This datetime field should be dropped

2023-09-14 13:05 UTC, jbaudoux commented on stock_release_channel_cutoff/readme/DESCRIPTION.rst
> +This module lets users select a release channel and set a specific cutoff time for it.
```suggestion
This module allows to set a cutoff time on a release channel.

```

2023-09-14 13:05 UTC, jbaudoux commented on stock_release_channel_cutoff/views/stock_release_channel_views.xml
> +            </xpath>
Can you find a way to have the cutoff time displayed before the process end time ? You can depend on the later module. It does not make sense to have a cutoff without end time
![image](https://github.com/OCA/wms/assets/7802725/0ebbc864-752c-4125-8bb4-127e68b22e50)

Also align your green with the other greens

2023-09-14 13:05 UTC, jbaudoux commented on stock_release_channel_cutoff/views/stock_release_channel_views.xml
> +            <field name="release_forbidden" position="after">
Move field above end time as this is a setting and not an option
![image](https://github.com/OCA/wms/assets/7802725/e0cea460-9cbd-4f0d-bb66-2c849636486c)

2023-09-14 13:05 UTC, jbaudoux commented on stock_release_channel_cutoff/readme/DESCRIPTION.rst
> +When the current time (now) becoms later than the cutoff time, the kanban view for that channel will display the cutoff time in red as a warning.
```suggestion
When the current time (now) becomes later than the cutoff time, and the channel is still open, the kanban view for that channel will display the cutoff time in red as a warning.
```

2023-09-19 09:27 UTC, QuocDuong1306 commented
Thank @jbaudoux a lot, I updated, could you review again, thanks

2023-09-19 10:14 UTC, jbaudoux approved these changes
LG, last fixes not tested yet

2023-09-21 06:53 UTC, cyrilmanuel approved these changes
lgtm

2023-10-05 09:03 UTC, jbaudoux requested changes

2023-10-05 09:03 UTC, jbaudoux commented on stock_release_channel_cutoff/models/stock_release_channel.py
> +                datetime = now.replace(
To prevent to have a warning on channels planned for the days in the future
```suggestion
                datetime = process_end_date.replace(
```

2023-10-05 09:06 UTC, jbaudoux commented on stock_release_channel_cutoff/views/stock_release_channel_views.xml
> +                    decoration-danger="state == 'open' and cutoff_warning"
This is not very readable. Can you instead keep text in white and display background in red?
![image](https://github.com/OCA/wms/assets/7802725/70a5dce6-c931-4587-bbcb-ccf3415f6793)

2023-10-06 07:18 UTC, QuocDuong1306 commented
The PR has been updated, more depending on #760 for `tests` and `pre-commit`

2023-10-06 08:01 UTC, jbaudoux approved these changes
LG, thanks

2023-10-09 06:26 UTC, simahawk commented
Rebased and fixed minor glitches

2023-10-09 06:38 UTC, simahawk commented
/ocabot merge nobump

2023-10-09 06:48 UTC, merged