[14.0][IMP] shopfloor: imp cancel line/package in location content transfer
OCA/wms pull request #748
Opened 2023-09-14 07:49 UTC by TDu

ref.: rau-229

2023-09-18 09:00 UTC, jbaudoux requested changes

2023-09-18 09:00 UTC, jbaudoux commented on shopfloor/services/location_content_transfer.py
> +            move._action_cancel()
Looks good to call `_action_cancel` before before creating the stock issue.
`_action_cancel` is already doing the `_do_unreserve`
```suggestion
            move._action_cancel()
```

Also update docstring

2023-09-18 09:00 UTC, jbaudoux commented on shopfloor/services/location_content_transfer.py
> +                package_move._action_cancel()
Looks good to call `_action_cancel` before before creating the stock issue.
`_action_cancel` is already doing the `_do_unreserve`
```suggestion
            move._action_cancel()
```

Also update docstring

2023-09-18 09:00 UTC, jbaudoux commented on shopfloor/services/location_content_transfer.py
> +                stock.unmark_move_line_as_picked(package_move.move_line_ids)
We also need to unreserve before creating the stock issue.

2023-09-18 09:00 UTC, jbaudoux commented on shopfloor/services/location_content_transfer.py
> +            stock.unmark_move_line_as_picked(move.move_line_ids)
We also need to unreserve before creating the stock issue.

2023-09-19 14:01 UTC, jbaudoux approved these changes
LGTM

2023-09-19 20:04 UTC, mt-software-de approved these changes
LG

2023-11-27 10:02 UTC, jbaudoux commented
@Tdu Rebase & squash fixup

2023-11-27 10:23 UTC, TDu commented
@jbaudoux Squashed and rebased

2023-11-27 12:06 UTC, jbaudoux commented
/ocabot merge minor

2023-11-27 12:21 UTC, merged