[14.0][IMP] shopfloor: imp cancel on single pack transfer
OCA/wms pull request #749
Opened 2023-09-14 15:04 UTC by TDu

Before the package level was only set as not done, when calling the cancel route.

Now if the package level has been created by the
current shopfloor user, its related transfer is also canceled.

2023-09-18 11:06 UTC, jbaudoux requested changes

2023-09-18 11:06 UTC, jbaudoux commented on shopfloor/services/single_pack_transfer.py
> +        if package_level.picking_id.create_uid == self.env.user:
```suggestion
        if self.is_allow_move_create() and package_level.picking_id.create_uid == self.env.user:
```

2023-09-18 11:06 UTC, jbaudoux commented on shopfloor/services/single_pack_transfer.py
> +            moves.picking_id.action_cancel()
You can drop the 2 first lines, action_cancel is doing it

2023-09-18 11:06 UTC, jbaudoux commented on shopfloor/services/single_pack_transfer.py
> +        if package_level.picking_id.create_uid == self.env.user:
and where is the else mark picking as unpicked like you just did on the other scenario in https://github.com/OCA/wms/pull/748 ?

2023-09-19 14:02 UTC, jbaudoux approved these changes
LGTM

2023-09-19 20:04 UTC, mt-software-de approved these changes
LG

2023-11-21 15:18 UTC, jbaudoux commented
/ocabot merge minor

2023-11-21 16:00 UTC, merged