[16.0][IMP] stock_available_to_promise_release: Unrelease when merging moves
OCA/wms pull request #834
Opened 2024-02-08 16:02 UTC by lmignon

When moves are merged into an outgoing picking and the product_uom_qty is updated it's important to unrelease the move since the release process has been done for the previous qty. This case occurs for example when the qty is modified for a line on a confirmed SO.

2024-02-08 16:02 UTC, lmignon commented
cc @rousseldenis @jbaudoux

2024-02-09 11:46 UTC, flotho approved these changes
Code review
Principle understood
LGTM

2024-02-19 14:57 UTC, rousseldenis approved these changes
Code review

2024-02-29 10:11 UTC, TDu approved these changes

2024-05-07 14:19 UTC, jbaudoux requested changes

2024-05-07 14:19 UTC, jbaudoux commented on stock_available_to_promise_release/models/stock_move.py
> +            to_unrelease.unrelease()
You should not unrelease if it is not allowed (like started)
```suggestion
            to_unrelease.unrelease(safe_unrelease=True)
```

2024-05-16 06:40 UTC, rousseldenis commented
@jbaudoux

2024-06-12 10:11 UTC, jbaudoux requested changes

2024-06-12 10:11 UTC, jbaudoux commented on stock_available_to_promise_release/models/stock_move.py
> +            to_unrelease.unrelease(safe_unrelease=True)
You need to check move `_is_unreleaseable()` first.
If it cannot be unreleased, we must raise an error. For this, you need `safe_unrelease=False`
If you unrelease, I would release again after the merge

2024-10-14 08:12 UTC, jbaudoux commented
ping @lmignon

2024-10-14 08:37 UTC, lmignon commented
> ping @lmignon

I'm on it.

2024-10-14 13:26 UTC, lmignon commented
@jbaudoux Your remarks are taken into account now.

2024-10-14 13:42 UTC, jbaudoux approved these changes

2024-10-14 13:44 UTC, jbaudoux commented
/ocabot merge minor

2024-10-14 13:54 UTC, merged