[IMP] stock_release_channel_process_end_time: process_end_date as dat…
OCA/wms pull request #836
Opened 2024-02-09 16:34 UTC by lmignon

…e_deadline

Add a new option on the route definition to allow the use of the release channel's process end date as date deadline on stock moves created when releasing deliveries. This is required to allow the merge of generated moves. By default pulled moves keep the date deadline of their destination moves. If different moves for the same product from different sale orders are grouped into the same delivery, you expect that the system will generate only one pick operation. It's only possible if the generated pulled moves have the same date deadline.

2024-02-09 16:35 UTC, lmignon commented
cc @jbaudoux

2024-02-10 07:05 UTC, jbaudoux requested changes

2024-02-10 07:05 UTC, jbaudoux commented on stock_release_channel_process_end_time/models/stock_picking.py
> +            super(StockPicking, pickings).release_available_to_promise()
Instead of using a context value, can't you override `_prepare_procurement_values` on `stock.move` ?

Sth like:
```
if self.picking_type_code == "outgoing" and self.picking_id.release_channel_id.process_end_date:
  values["date_deadline"] = process_end_date
```

2024-02-10 07:05 UTC, jbaudoux commented on stock_release_channel_process_end_time/models/stock_route.py
> +    propagate_process_end_date_as_move_date_deadline = fields.Boolean(
We already have option `stock_release_use_channel_end_date` in the settings. Can't we use that one? I don't think we need a new one.
I would at least keep the parameters there and not spread them.

2024-02-10 07:05 UTC, jbaudoux commented on stock_release_channel_process_end_time/readme/DESCRIPTION.rst
> +When managing deliveries through a release channel two main issues are faced:
```suggestion
This module allows to configure an end time on a release channel that will become the channel end date when the channel awakes. This process end date specify when all the work in the channel should be finalized.
Note: ensure to configure the timezone on the address of the warehouse to have the right time to datetime conversion.

The channel process end date can be propagated to the generated pickings in order to solve two challenges:
```

2024-02-10 07:05 UTC, jbaudoux commented on stock_release_channel_process_end_time/readme/DESCRIPTION.rst
> +This module solves these issues.
```suggestion
```

2024-02-12 08:48 UTC, lmignon commented on stock_release_channel_process_end_time/models/stock_picking.py
> +            super(StockPicking, pickings).release_available_to_promise()
It was my first thought. I finally choose  this approach to make the 'propagate' configurable on the route. I'll simplify all the approach to only rely oh the option into the global settings.

2024-02-14 12:16 UTC, jbaudoux approved these changes
Thanks for the changes

2024-02-19 14:59 UTC, rousseldenis approved these changes
Code review

2024-04-03 21:03 UTC, jbaudoux commented
/ocabot merge minor

2024-04-04 07:05 UTC, jbaudoux commented
@lmignon Can you rebase?

2024-04-04 12:54 UTC, sbejaoui commented
> @lmignon Can you rebase?

done

2024-04-04 21:54 UTC, jbaudoux commented
/ocabot merge minor

2024-04-04 22:03 UTC, merged