[16.0][ADD] stock_release_channel_delivery
OCA/wms pull request #840
Opened 2024-02-21 02:56 UTC by trisdoan

2024-02-22 15:20 UTC, jbaudoux commented
@trisdoan Can you rewrite commit msg
`[IMP] implement JE's change requests`
to 
```[IMP] stock_release_channel_delivery:

allow to configure multiple shipping methods on a channel```

2024-02-22 15:24 UTC, jbaudoux commented
Note: failing test is not related to this PR

2024-02-22 15:29 UTC, jbaudoux reviewed
LG.
Can you also fix the translations

2024-02-22 15:29 UTC, jbaudoux commented on stock_release_channel_delivery/i18n/fr.po
> +msgstr "Transporteur"
```suggestion
#: model:ir.model.fields,field_description:stock_release_channel_delivery.field_stock_release_channel__carrier_ids
msgid "Shipping Methods"
msgstr "Méthodes de livraison"
```

2024-02-22 15:29 UTC, jbaudoux commented on stock_release_channel_delivery/i18n/fr.po
> +msgstr "Le transporteur associé au release channel"
```suggestion
#: model:ir.model.fields,help:stock_release_channel_delivery.field_stock_release_channel__carrier_ids
msgid "The shipping methods linked to the release channel."
msgstr "Les méthodes de livraisons associées au release channel"
```

2024-02-22 15:29 UTC, jbaudoux commented on stock_release_channel_delivery/i18n/stock_release_channel_delivery.pot
> +msgid "The carrier linked to the release channel."
```suggestion
#: model:ir.model.fields,help:stock_release_channel_delivery.field_stock_release_channel__carrier_ids
msgid "The shipping methods linked to the release channel."
```

2024-02-22 15:29 UTC, jbaudoux commented on stock_release_channel_delivery/i18n/stock_release_channel_delivery.pot
> +msgid "Transporter"
```suggestion
#: model:ir.model.fields,field_description:stock_release_channel_delivery.field_stock_release_channel__carrier_ids
msgid "Shipping Methods"
```

2024-02-27 15:54 UTC, sebalix commented
Build fixed here: https://github.com/OCA/wms/pull/849

2024-03-20 13:47 UTC, jbaudoux commented
@trisdoan Can you rebase this one ?

2024-03-21 15:40 UTC, trisdoan commented
Hello @jbaudoux, it's done

2024-03-21 15:42 UTC, jbaudoux approved these changes

2024-03-21 15:43 UTC, jbaudoux commented
Thanks

2024-03-21 15:46 UTC, jbaudoux commented
ping @rousseldenis @lmignon

2024-03-22 07:43 UTC, rousseldenis commented on stock_release_channel_delivery/migrations/16.0.2.0.0/pre-migration.py
> +    if openupgrade.column_exists(env.cr, "stock_release_channel", "carrier_id"):
@trisdoan @jbaudoux Doesn't this conflict with post script ?

2024-03-22 07:44 UTC, rousseldenis commented on stock_release_channel_delivery/models/stock_picking.py
> +                    ("carrier_ids", "=", self.carrier_id.ids),
Don't you have a warning as "in" is better IMHO?

2024-03-22 07:45 UTC, rousseldenis commented on stock_release_channel_delivery/models/stock_picking.py
> +                    ("carrier_ids", "=", self.carrier_id.ids),
Indeed, you have:

![image](https://github.com/OCA/wms/assets/19529533/d0419868-124e-4d2a-9d3f-356115cfcdda)

2024-03-22 07:46 UTC, rousseldenis requested changes
Code review

2024-03-22 08:13 UTC, jbaudoux commented on stock_release_channel_delivery/migrations/16.0.2.0.0/pre-migration.py
> +    if openupgrade.column_exists(env.cr, "stock_release_channel", "carrier_id"):
That's per documentation in https://oca.github.io/openupgradelib/API.html#openupgradelib.openupgrade.m2o_to_x2m

How should it be according to you?

2024-03-22 10:54 UTC, rousseldenis commented on stock_release_channel_delivery/migrations/16.0.2.0.0/pre-migration.py
> +    if openupgrade.column_exists(env.cr, "stock_release_channel", "carrier_id"):
But you rename the column to nothing ?

2024-03-22 10:55 UTC, rousseldenis commented on stock_release_channel_delivery/migrations/16.0.2.0.0/pre-migration.py
> +    if openupgrade.column_exists(env.cr, "stock_release_channel", "carrier_id"):
Ooooh, ok didn't know the legacy name

2024-03-22 16:06 UTC, trisdoan commented
Hello @rousseldenis, thank you for your in-depth review.

I updated as you suggested.

2024-03-26 11:14 UTC, cyrilmanuel approved these changes
Not an expert but LGTM

@rousseldenis  little ping, is it good for you ?

2024-03-26 13:55 UTC, lmignon approved these changes
LGTM (Code review)

2024-03-27 07:48 UTC, jbaudoux commented
/ocabot merge nobump

2024-03-27 07:56 UTC, merged