[16.0] stock_release_channel: multi-company support
OCA/wms pull request #842
Opened 2024-02-23 08:00 UTC by sebalix

2024-08-27 10:38 UTC, jbaudoux requested changes
I would also add on:
* stock_release_channel
  * picking_ids `check_company=True` 
* shipment_advice
  * dock_id : `domain="[('warehouse_id', '=', warehouse_id)]"`
  * planned_move_ids `check_company=True`
  * loaded_move_lines_ids `check_company=True`
  * loaded_move_lines_without_package_ids `check_company=True`

2024-08-27 10:38 UTC, jbaudoux commented on stock_release_channel/models/stock_picking.py
> +            ("company_id", "=", self.picking_type_id.company_id.id),
```suggestion
            ("company_id", "=", self.company_id.id),
```

2024-08-27 10:38 UTC, jbaudoux commented on stock_release_channel/models/stock_release_channel.py
> +        check_company=True,
You cannot use both domain and check_company on the field. You need to add `("company_id", "in", (company_id, False))` in the domain

2024-08-27 10:38 UTC, jbaudoux commented on stock_release_channel/models/stock_release_channel.py
> +        domain="['|', ('company_id', '=', company_id), ('company_id', '=', False)]",
Here you can use
```suggestion
        check_company=True,
```

2024-08-27 11:35 UTC, sebalix commented on stock_release_channel/models/stock_picking.py
> +            ("company_id", "=", self.picking_type_id.company_id.id),
`<stock.picking>.company_id` is not required, while it is on `<stock.picking.type>`

2024-08-27 14:53 UTC, jbaudoux commented on stock_release_channel/models/stock_picking.py
> +            ("company_id", "=", self.picking_type_id.company_id.id),
But you are processing a picking, so better use its company.
I guess they forgot the required=True and we can assume there will always be one

2024-09-24 13:32 UTC, jbaudoux approved these changes
LG. Thanks. Can you keep one commit per module ?

Do you do the implementation also in the transport repo?

2024-09-24 13:50 UTC, jbaudoux commented
@lmignon Is checking the toursolver failing test case. He fixed it in transport repo. I don't know why it is still complaining here

2024-09-24 13:58 UTC, jbaudoux commented
> @lmignon Is checking the toursolver failing test case. He fixed it in transport repo. I don't know why it is still complaining here

fixed here https://github.com/OCA/wms/pull/928

2024-09-24 14:24 UTC, lmignon approved these changes
LGTM (Code review only)

2024-09-24 16:03 UTC, sebalix commented
@jbaudoux there is one commit per module yes. I'll do the changes on `shipment_advice` yes

2024-09-24 16:08 UTC, sebalix commented
https://github.com/OCA/stock-logistics-transport/pull/146

2024-09-24 16:41 UTC, jbaudoux commented
/ocabot merge minor

2024-09-24 17:00 UTC, merged