[16.0][ADD]: sale_stock_available_to_promise_release add ir.config_pa…
OCA/wms pull request #896
Opened 2024-04-30 07:10 UTC by victorvermot

…rameter

2024-04-30 11:09 UTC, santostelmo commented on sale_stock_available_to_promise_release/models/res_config_settings.py
> +    display_is_available = fields.Boolean(
IMO This should be true by default and related to the company. You maybe want to show this field only in some companies

2024-04-30 11:10 UTC, santostelmo commented on sale_stock_available_to_promise_release/reports/sale_order.xml
> +                t-if="doc.state != 'draft' and doc.env['ir.config_parameter'].sudo().get_param('sale_stock_available_to_promise_release.display_is_available')"
```suggestion
                t-if="doc.state != 'draft' and doc.company_id.display_is_available"
```
As mentioned above if you configure by company then you can do something like that.

2024-05-01 09:42 UTC, santostelmo commented on sale_stock_available_to_promise_release/models/res_config_settings.py
> +        config_parameter="sale_stock_available_to_promise_release.display_is_available",
Do you need config parameter ?

2024-05-01 10:06 UTC, cyrilmanuel approved these changes

2024-05-01 10:15 UTC, santostelmo approved these changes

2024-05-01 11:02 UTC, victorvermot commented on sale_stock_available_to_promise_release/models/res_config_settings.py
> +        config_parameter="sale_stock_available_to_promise_release.display_is_available",
you're right I removed it

2024-05-01 12:38 UTC, leemannd approved these changes

2024-05-03 08:00 UTC, sebalix requested changes

2024-05-03 08:00 UTC, sebalix commented on sale_stock_available_to_promise_release/models/res_company.py
> +    display_is_available = fields.Boolean(
The name of this field is too generic for `res.company` and could conflict with another field name easily with all modules installed on an Odoo instance.
What about `sale_stock_report_display_is_available` or `stock_sale_report_display_is_available` (as all other settings are prefixed with `stock_` in the parent module).

2024-05-03 08:00 UTC, sebalix commented on sale_stock_available_to_promise_release/models/res_config_settings.py
> +        help="Show Available column in SO and quotation reports",
I think you can remove the `help` here, it'll come from the original field automatically.

2024-05-03 08:00 UTC, sebalix commented on sale_stock_available_to_promise_release/views/res_config_settings.xml
> +            <xpath expr="//div[@id='annual_inventory_date']" position="after">
There is already a section introduced by the parent module to host settings related to the release features: https://github.com/OCA/wms/blob/16.0/stock_available_to_promise_release/views/res_config_settings.xml#L13C64-L13C81
Better to place the new setting in this section.

2024-05-22 14:04 UTC, sebalix approved these changes

2024-05-27 07:53 UTC, jbaudoux approved these changes

2024-05-27 07:55 UTC, jbaudoux commented on sale_stock_available_to_promise_release/models/res_company.py
> +        default=True,
Shouldn't this be `False` by default ?

cc @sebalix

2024-05-27 13:47 UTC, sebalix commented on sale_stock_available_to_promise_release/models/res_company.py
> +        default=True,
Before this PR the column was always displayed, we are only adding an option here to hide it, but by default we keep it displayed as before. No?

2024-05-27 14:31 UTC, jbaudoux commented on sale_stock_available_to_promise_release/models/res_company.py
> +        default=True,
all good then :)

2024-05-27 14:32 UTC, jbaudoux commented
@victorvermot Can you drop `[16.0][ADD]: ` from the commit message ?

2024-06-19 07:56 UTC, sebalix commented
/ocabot merge minor

2024-06-19 09:58 UTC, merged