[REF] shopfloor_reception
OCA/wms pull request #907
Opened 2024-05-29 10:29 UTC by vnikolayev1

- updated shopfloor_reception - changed done_action and move the call of _action_done only into _handle_backorder. This ensures if _handle_backorder is called the picking is set to done

2024-05-29 10:32 UTC, vnikolayev1 commented
@mt-software-de

2024-05-29 19:01 UTC, mt-software-de requested changes
Thx. There is just a small mistake.

2024-05-29 19:01 UTC, mt-software-de commented on shopfloor_reception/services/reception.py
> +    def _handle_backorder(self, picking, cancel_backorder=False):
You forgot to Set Argument `cancel_backorder` in Line 997

2024-06-04 11:42 UTC, jbaudoux reviewed
I don't understand what you are fixing. Can you clarify what was not working?

2024-06-04 11:52 UTC, mt-software-de commented
> I don't understand what you are fixing. Can you clarify what was not working?

It is not a fix it is a refactoring. 😂 @vnikolayev1 could please update the title of this PR.

2024-06-04 11:56 UTC, mt-software-de requested changes

2024-06-04 11:56 UTC, mt-software-de commented on shopfloor_reception/services/reception.py
> +        self._handle_backorder(picking, True)
We not want to cancel the Backorder Always please Pass the cancel_backorder var. 
```suggestion
        self._handle_backorder(picking, cancel_backorder)
```

2024-06-04 13:45 UTC, jbaudoux commented
> It is not a fix it is a refactoring. 😂 @vnikolayev1 could please update the title of this PR.

A refactor to do what if it is not fixing nor improving anything?

2024-06-04 17:17 UTC, mt-software-de commented
> > It is not a fix it is a refactoring. 😂 @vnikolayev1 could please update the title of this PR.
> 
> A refactor to do what if it is not fixing nor improving anything?

It is improving the Code, with this change there is only one call of `picking._action_done`

2024-07-09 12:01 UTC, mt-software-de approved these changes
@jbaudoux could we merge this? Otherwise close it. From our side it is not needed anymore.

2024-10-04 13:40 UTC, jbaudoux approved these changes

2024-10-04 13:40 UTC, jbaudoux commented
/ocabot merge minor

2024-10-04 13:54 UTC, merged