[ADD] stock_available_to_promise_release_restrict_lot
OCA/wms pull request #943
Opened 2024-10-29 19:00 UTC by sbejaoui

When both stock_available_to_promise_release and stock_restrict_lot modules are installed, the calculation of quantities available to promise doesn't properly account for lot restrictions. This results in a priority conflict, where higher-priority moves that are restricted to a specific lot receive available quantities from any lot, bypassing their lot restriction.

This glue module enhances stock move allocation by:
- Allowing stock moves to respect both priority and specific lot allocations.
- Ensuring that available quantities are promised according to move priority, but only when the lot matches the restriction.

2024-10-30 07:18 UTC, lmignon requested changes
A little comment about readability...

2024-10-30 07:18 UTC, lmignon commented on stock_available_to_promise_release_restrict_lot/models/stock_move.py
> +        ]
This domain is really hard to read. The use of the AND and OR operators from the expressions module should improve readability ant therefore maintenance.

2024-12-31 10:18 UTC, jbaudoux requested changes
I wonder how this can work

2024-12-31 10:18 UTC, jbaudoux commented on stock_available_to_promise_release_restrict_lot/models/stock_move.py
> +        sql += "AND m.restrict_lot_id is null"
I would not do this. If you place a move without restrict lot, any move before should reserve a qty no matter they are restricted to a lot or not.
Example:
Move1 for lotA
Move2 for any lot. Should consider the previous Move1 taking from stock

2024-12-31 10:18 UTC, jbaudoux commented on stock_available_to_promise_release_restrict_lot/models/stock_move.py
> +        )
Seems to miss quite a few things in this domain: need_release, outgoing, picking type, locations...

2025-06-08 12:14 UTC, closed without merging