[16.0][FW] stock_storage_type: port changes from 14
OCA/wms pull request #948
Opened 2024-11-18 17:16 UTC by henrybackman

Port changes from 14.0 to 16.0. (No PRs)

The following PRs have been blacklisted:
- #264: (auto) Nothing to port from PR #264
- #269: (auto) Nothing to port from PR #269
- #723: (auto) Nothing to port from PR #723
- #772: dotfiles

2024-11-18 17:21 UTC, rousseldenis commented on stock_storage_type/models/stock_quant_package.py
> +    package_storage_type_id = fields.Many2one(
@henrybackman @grindtildeath What is the behavior on an existing database ?
IMHO, this compute will last a long time

2024-11-18 18:17 UTC, jbaudoux requested changes
You can blacklist all those changes, it's all covered.

What has been lost in the migration is the max_height field on the `stock.storage.category`. It's in the model but not in the view. Can be added after the`max_weight`.

Ideally all remaining mentions to `location_storage_types` should be renamed to `location_category` to make the code clearer. FYI the relation is now one instead of multi.

Finally, I wish to move changes to `StorageCategoryProductCapacity` to a new object. I can explain you in details if you want to help on this.

2024-11-18 18:17 UTC, jbaudoux commented on stock_storage_type/security/ir.model.access.csv
> +access_stock_location_package_storage_type_rel_manager,access_stock_location_package_storage_type_rel_manager,model_stock_location_package_storage_type_rel,base.group_user,1,1,1,1
All those models are gone in v16

2024-11-18 18:17 UTC, jbaudoux commented on stock_storage_type/models/stock_quant_package.py
> +    package_storage_type_id = fields.Many2one(
it is already there in standard and now named `package_type_id`

2024-11-18 18:17 UTC, jbaudoux commented on stock_storage_type/models/stock_quant_package.py
> +    def _compute_package_storage_type_id(self):
It's already there in v16: https://github.com/OCA/wms/blob/16.0/stock_storage_type/models/stock_quant_package.py#L56

2024-11-29 15:18 UTC, jbaudoux approved these changes

2024-11-29 15:20 UTC, jbaudoux commented
/ocabot merge nobump

2024-11-29 15:31 UTC, merged